// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, name sql.NullString) (sql.Result, error)
	// 物理削除ではなく、現在時刻を入れて「論理削除」にする
	DeleteUser(ctx context.Context, id uint64) error
	GetUser(ctx context.Context, id uint64) (User, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
